name: Attempt To Output From Inline Python Script
description: An action to attempt outputting data from an inline python script in a composite action
runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        repository: AlexWilson-GIS/Test-Export-Job-Output-From-Python-Script-Called-From-Inline-Script
        path: test
    - name: Output Data
      run: python ${{ github.action_path }}test/testOutput.py
      shell: sh
    #  env:
    #    PYTHONPATH: ${{ github.action_path }}test
    #  run: import testOutput
    #  shell: python