name: Test Job Output From Inline Python

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/TestJobOutputFromInlinePython.yml
      - action.yml
      - testOutput.py
  push:
    paths:
      - .github/workflows/TestJobOutputFromInlinePython.yml
      - action.yml
      - testOutput.py

jobs:
  GenerateOutput:
    name: Generate Job Output From Composite Action With Inline Python Script
    runs-on: [ubuntu-latest]
    outputs:
      TEST_DATA: ${{steps.testAction.outputs.MYOUTPUT}}
      TEST_DATA_FROM_SHELL: ${{steps.testAction.outputs.SHELL_OUTPUT}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Output Sample JSON
        id: testAction
        uses: ./
  UseOutput:
    name: Use Output From Previous Job
    needs: GenerateOutput
    runs-on: [ubuntu-latest]
    steps:
      - name: Echo Data
        run: echo ${{needs.GenerateOutput.outputs.TEST_DATA}}
        shell: sh
  UseShellOutput:
    name: Use Output Generate From Shell In Previous Job
    needs: GenerateOutput
    runs-on: [ubuntu-latest]
    steps:
      - name: Echo Shell Data
        run: echo ${{needs.GenerateOutput.outputs.TEST_DATA_FROM_SHELL}}
        shell: sh